orbs:
  node: circleci/node@2.0.2
  aws-cli: circleci/aws-cli@2.0.0
jobs:
  Test:
    machine:
      enabled: true
    steps:
      - run:
         name: test
         aws-access-key-id: AWS_ACCESS_KEY_ID
         aws-secret-access-key: AWS_SECRET_ACCESS_KEY
         region: AWS_DEFAULT_REGIO
         backgroundcommand: ssh ec2-ubuntu@ec2-13.235.68.44.ap-south-1.compute.amazonaws.com 'echo "ash"';
         command: ssh ec2-ubuntu@172-31-11-238.ap-south-1.compute.amazonaws.com 'mkdir test.txt';
version: 2.1
workflows:
  build_and_deploy:
    jobs:
      - Test:
          filters:
            branches:
              only: main
