orbs:
  node: circleci/node@2.0.2
  aws-cli: circleci/aws-cli@2.0.0
jobs:
  build_and_deploy:
    machine:
      enabled: true
    steps:
      - run:
         name: deploy
         aws-access-key-id: AWS_ACCESS_KEY_ID
         aws-secret-access-key: AWS_SECRET_ACCESS_KEY
         region: AWS_DEFAULT_REGIO
         backgroundcommand: ssh ubuntu@13.235.68.44.ap-south-1.compute.amazonaws.com 'echo "ash"';
         command: ssh u ssh -o StrictHostKeyChecking=no ubuntu@13-126-32-219;
version: 2.1
workflows:
  build_and_deploy:
    jobs:
      - build_and_deploy:
          filters:
            branches:
              only: main
